from moviepy.editor import VideoFileClip, concatenate_videoclips
clip1 = VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight1.mp4")
clip2 = VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight2.mp4")
clip3 = VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight3.mp4")
clip4 = VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight5.mp4")
clip5 = VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight6.mp4")
clip6 = VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight7.mp4")
clip7 = VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight8.mp4")
clip8 = VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight9.mp4")
clip9 = VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight10.mp4")
clip10 = VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight11.mp4")
clip11= VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight12.mp4")
clip12 = VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight13.mp4")
clip13= VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight14.mp4")
clip14= VideoFileClip("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\highlight4.mp4")

final_clip = concatenate_videoclips([clip1,clip2,clip3,clip4,clip5,clip6,clip7,clip8,clip9,clip9,clip10,clip11,clip12,clip13,clip14])
final_clip.write_videofile("C:\\Users\\Kunal Dhariwal\\PycharmProjects\\final_highlights.mp4")
